persistence:
  enabled: true
  size: 100
  storageClass: managed-csi-premium

nodeSelector:
  kubernetes.io/arch: amd64
  jenkins: ci.jenkins.io
  role: applications

tolerations:
  - key: "ci.jenkins.io/applications"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: "app.kubernetes.io/name"
              operator: In
              values:
                - artifact-caching-proxy
        topologyKey: "kubernetes.io/hostname"

service:
  type: LoadBalancer
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    # TODO: track with updatecli
    service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "public-jenkins-sponsorship-vnet-ci_jenkins_io_agents"
    # TODO: track with updatecli
    service.beta.kubernetes.io/azure-load-balancer-ipv4: "10.200.2.254"
    service.beta.kubernetes.io/azure-load-balancer-disable-tcp-reset: "true"

resources:
  limits:
    # No CPU limit to avoid throttling
    memory: 8192Mi
  requests:
    cpu: 1.5
    memory: 8192Mi

replicaCount: 1

proxy:
  dnsResolver: "kube-dns.kube-system.svc.cluster.local 9.9.9.9"
  proxySslServerNameEnabled: true # Pass SNI to upstreams
