service:
  type: LoadBalancer
  # Public IPv4 defined as code in https://github.com/jenkins-infra/azure/blob/main/ldap.jenkins.io.tf instead of requesting a random new public IP, useful for DNS setup and changes
  # TODO: automate syncing
  azurePip:
    name: ldap-jenkins-io-ipv4
    resourceGroup: prod-public-ips
  lbAllowSources:
    publick8s-out-lb-1: '20.85.71.108/32'
    publick8s-out-lb-2: '20.22.30.9/32'
    publick8s-out-lb-3: '20.22.30.74/32'
    publick8s-nat: '20.7.192.189/32'
    publick8s-pods: '10.100.0.0/16'
    # TODO: remove
    spambot: '73.71.177.172/32'
    # TODO: remove (old OSUOSL IP)
    accounts.jenkins.io: '140.211.15.101/32'
    puppet.jenkins.io: '20.12.27.65/32'
    trusted.ci.jenkins.io: '104.209.128.236/32'
    private.vpn.jenkins.io: '172.176.126.194/32'
    cert.ci.jenkins.io: '104.209.153.13/32'
    linuxfoundation-staging: '34.211.101.61/32'
    linuxfoundation-prod: '44.240.22.235/32'
    privatek8s-out-lb-1: '20.22.6.81/32'
    privatek8s-nat: '20.65.63.127/32'
    # https://jfrog.com/knowledge-base/what-are-artifactory-cloud-nated-ips/
    jfrog-artifactory: '18.214.241.149/32,34.201.191.93/32,34.233.58.83/32,54.236.124.56/32'
    aws.ci.jenkins.io: '3.146.166.108/32'

resources:
  limits:
    cpu: 2
    memory: 2048Mi
  requests:
    cpu: 200m
    memory: 512Mi

nodeSelector:
  kubernetes.io/arch: amd64

tolerations:
  - key: "kubernetes.io/arch"
    operator: "Equal"
    value: "arm64"
    effect: "NoSchedule"

persistence:
  # Tracked by updatecli
  customDataClaimName: ldap-jenkins-io-data
  # Tracked by updatecli
  customBackupClaimName: ldap-jenkins-io-backup
