name: Update list of IPs allowed to access LDAP

scms:
  default:
    kind: github
    spec:
      user: "{{ .github.user }}"
      email: "{{ .github.email }}"
      owner: "{{ .github.owner }}"
      repository: "{{ .github.repository }}"
      token: "{{ requiredEnv .github.token }}"
      username: "{{ .github.username }}"
      branch: "{{ .github.branch }}"

sources:
  puppet.jenkins.io:
    kind: json
    spec:
      file: https://reports.jenkins.io/jenkins-infra-data-reports/azure.json
      key: .puppet\.jenkins\.io.outbound_ips
    transformers:
      - addprefix: "'"
      - addsuffix: '/32'
      - addsuffix: "'"

  publick8s-lb:
    kind: json
    spec:
      file: https://reports.jenkins.io/jenkins-infra-data-reports/azure.json
      key: .publick8s.lb_outbound_ips.ipv4
    transformers:
      - trimprefix: '['
      - trimsuffix: ']'
      - replacer:
          from: ' '
          to: '/32,'
      - addsuffix: '/32'
      - addprefix: "'"
      - addsuffix: "'"

  publick8s-pods:
    kind: json
    spec:
      file: https://reports.jenkins.io/jenkins-infra-data-reports/azure.json
      # Ipv4 is always the first element
      key: .publick8s.pod_cidrs.[0]
    transformers:
      - addprefix: "'"
      - addsuffix: "'"

  # https://jfrog.com/knowledge-base/what-are-artifactory-cloud-nated-ips/
  jfrog:
    kind: json
    spec:
      file: https://my.jfrog.com/api/jmis/v1/ip-ranges
      # Dasel v1 query
      key: .(cloud=aws)(region=us-east-1)(service=jfrog_cloud_cidr).cidr
    # Change the json list to a comma-separated list into a single string
    transformers:
      - trimprefix: '['
      - trimsuffix: ']'
      - replacer:
          from: ' '
          to: ','

  azure-ci-jenkins-io:
    kind: json
    spec:
      file: https://reports.jenkins.io/jenkins-infra-data-reports/azure-net.json
      # Outbound IPs are also public "inbound" IPs for EC2 instances
      # The 2nd element is the IPv4 (1st is IPv6)
      key: .ci\.jenkins\.io.outbound_ips
    # Change the json list to a comma-separated list into a single string
    transformers:
      - trimprefix: '['
      - trimsuffix: ']'
      - replacer:
          from: ' '
          to: '/32,'
      - addsuffix: "/32"

targets:
  puppet.jenkins.io:
    name: Update puppet.jenkins.io CIDR in the LDAP configuration
    kind: yaml
    sourceid: puppet.jenkins.io
    spec:
      file: config/ldap.yaml
      key: $.service.lbAllowSources.'puppet.jenkins.io'
    scmid: default

  publick8s-pods:
    name: Update publick8s pod CIDRs in the LDAP configuration
    kind: yaml
    sourceid: publick8s-pods
    spec:
      file: config/ldap.yaml
      key: $.service.lbAllowSources.publick8s-pods
    scmid: default

  publick8s-lb:
    name: Update publick8s outbound LB CIDRs in the LDAP configuration
    kind: yaml
    sourceid: publick8s-lb
    spec:
      file: config/ldap.yaml
      key: $.service.lbAllowSources.publick8s-out-lb
    scmid: default

  azure-ci-jenkins-io:
    name: Update azure.ci.jenkins.io CIDR in the LDAP configuration
    kind: yaml
    sourceid: azure-ci-jenkins-io
    spec:
      file: config/ldap.yaml
      key: $.service.lbAllowSources.'azure.ci.jenkins.io'
    scmid: default

  jfrog:
    name: Update JFrog CIDRs in the LDAP configuration
    kind: yaml
    sourceid: jfrog
    spec:
      file: config/ldap.yaml
      key: $.service.lbAllowSources.jfrog-artifactory
    scmid: default

actions:
  default:
    kind: github/pullrequest
    scmid: default
    title: Update list of IPs allowed to access LDAP
    spec:
      labels:
        - enhancement
        - ldap
