name: Update `maven-cacher` configuration

scms:
  default:
    kind: github
    spec:
      user: "{{ .github.user }}"
      email: "{{ .github.email }}"
      owner: "{{ .github.owner }}"
      repository: "{{ .github.repository }}"
      token: "{{ requiredEnv .github.token }}"
      username: "{{ .github.username }}"
      branch: "{{ .github.branch }}"

sources:
  getPVCName:
    kind: json
    name: Retrieve the PVC name from the Terraform report
    spec:
      file: https://reports.jenkins.io/jenkins-infra-data-reports/azure.json
      key: azure\.ci\.jenkins\.io.agents_kubernetes_clusters.cijenkinsio_agents_1.maven_cache_pvcs.maven-cache

targets:
  updatePVCNameInConfig:
    name: Update PVC name in the configuration
    kind: yaml
    sourceid: getPVCName
    spec:
      file: ./config/cijioagents1-maven-cacher.yaml
      key: $.cachePvc
    scmid: default

actions:
  default:
    kind: github/pullrequest
    scmid: default
    title: Update `maven-cacher` configuration
    spec:
      labels:
        - maven-cacher
        - configuration
